/* Generated by zbus-architect. Do not edit by hand. */
#ifndef ZBUS_GENERATED_MESSAGES_H
#define ZBUS_GENERATED_MESSAGES_H

#include <stdint.h>
struct version_msg {
	uint8_t major;
	uint8_t minor;
	uint16_t build;
};
struct acc_msg {
	int x;
	int y;
	int z;
};

#endif /* ZBUS_GENERATED_MESSAGES_H */