/* Generated by zbus-architect. Do not edit by hand. */
#include "zbus_channels.h"
ZBUS_LISTENER_DEFINE_WITH_ENABLE(foo_lis, listener_callback_example, true);
ZBUS_SUBSCRIBER_DEFINE_WITH_ENABLE(bar_sub, 4, true);
ZBUS_ASYNC_LISTENER_DEFINE_WITH_ENABLE(baz_async_lis, async_listener_callback_example, true);