/* Generated by zbus-architect. Do not edit by hand. */
#include "zbus_channels.h"
ZBUS_LISTENER_DEFINE(foo_lis, listener_callback_example);
ZBUS_SUBSCRIBER_DEFINE(bar_sub, 4);
ZBUS_ASYNC_LISTENER_DEFINE(baz_async_lis, async_listener_callback_example);