/* Generated by zbus-architect. Do not edit by hand. */
#ifndef ZBUS_GENERATED_CHANNELS_H
#define ZBUS_GENERATED_CHANNELS_H

#include <zephyr/zbus/zbus.h>
ZBUS_CHAN_DEFINE(
    version_chan,                  /* Name */
    struct version_msg,          /* Message type */
    NULL,                             /* Validator */
    NULL,                             /* User data */
    ZBUS_OBSERVERS_EMPTY,
    ZBUS_MSG_INIT(.major = 0, .minor = 1,
			       .build = 2)
);
ZBUS_CHAN_DEFINE(
    acc_data_chan,                  /* Name */
    struct acc_msg,          /* Message type */
    NULL,                             /* Validator */
    NULL,                             /* User data */
    ZBUS_OBSERVERS(foo_lis, bar_sub, baz_async_lis),
    ZBUS_MSG_INIT(.x = 0, .y = 0, .z = 0)
);
ZBUS_CHAN_DEFINE(
    simple_chan,                  /* Name */
    int,          /* Message type */
    simple_chan_validator,
    NULL,                             /* User data */
    ZBUS_OBSERVERS_EMPTY,
    0
);

#endif /* ZBUS_GENERATED_CHANNELS_H */