"""Code generation for zbus C files."""

from __future__ import annotations

from jinja2 import BaseLoader, Environment

from .model import Architecture

_ZBUS_MESSAGES_H_TEMPLATE = """
/* Generated by zbus-architect. Do not edit by hand. */
#ifndef ZBUS_GENERATED_MESSAGES_H
#define ZBUS_GENERATED_MESSAGES_H

#include <stdint.h>

{%- for msg in architecture.messages %}
{%- if msg.fields %}
struct {{ msg.name }} {
{%- for f in msg.fields %}
    {{ f.type }} {{ f.name }}{% if f.array_size %}[{{ f.array_size }}]{% endif %};
{%- endfor %}
};
{%- elif msg.definition %}
{{ msg.definition }}
{%- endif %}
{%- endfor %}

#endif /* ZBUS_GENERATED_MESSAGES_H */
""".strip()

_ZBUS_CHANNELS_H_TEMPLATE = """
/* Generated by zbus-architect. Do not edit by hand. */
#ifndef ZBUS_GENERATED_CHANNELS_H
#define ZBUS_GENERATED_CHANNELS_H

#include <zephyr/zbus/zbus.h>
#include "zbus_messages.h"

{%- for chan in architecture.channels %}
ZBUS_CHAN_DEFINE(
    {{ chan.name }},                  /* Name */
    {{ chan.message_type }},          /* Message type */
    {%- if chan.validator %}
    {{ chan.validator }},
    {%- else %}
    NULL,                             /* Validator */
    {%- endif %}
    {%- if chan.user_data %}
    {{ chan.user_data }},
    {%- else %}
    NULL,                             /* User data */
    {%- endif %}
    {%- if chan.observers %}
    ZBUS_OBSERVERS({{ chan.observers | join(", ") }}),
    {%- else %}
    ZBUS_OBSERVERS_EMPTY,
    {%- endif %}
    {%- if chan.initial_value %}
    {{ chan.initial_value }}
    {%- else %}
    ZBUS_MSG_INIT(0)
    {%- endif %}
);
{%- endfor %}

{%- for obs in architecture.add_observations %}
ZBUS_CHAN_ADD_OBS(&{{ obs.channel }}, &{{ obs.observer }}{% if obs.priority %}, "{{ obs.priority }}"{% endif %});
{%- endfor %}

#endif /* ZBUS_GENERATED_CHANNELS_H */
""".strip()

_ZBUS_OBSERVERS_C_TEMPLATE = """
/* Generated by zbus-architect. Do not edit by hand. */
#include "zbus_channels.h"

{%- for obs in architecture.observers %}
{%- if obs.kind == "listener" %}
ZBUS_LISTENER_DEFINE_WITH_ENABLE({{ obs.name }}, {{ obs.callback }}, {{ 'true' if obs.enabled else 'false' }});
{%- elif obs.kind == "subscriber" %}
ZBUS_SUBSCRIBER_DEFINE_WITH_ENABLE({{ obs.name }}, {{ obs.queue_size or 1 }}, {{ 'true' if obs.enabled else 'false' }});
{%- elif obs.kind == "msg_subscriber" %}
ZBUS_MSG_SUBSCRIBER_DEFINE_WITH_ENABLE({{ obs.name }}, {{ 'true' if obs.enabled else 'false' }});
{%- elif obs.kind == "async_listener" %}
ZBUS_ASYNC_LISTENER_DEFINE_WITH_ENABLE({{ obs.name }}, {{ obs.callback }}, {{ 'true' if obs.enabled else 'false' }});
{%- endif %}
{%- endfor %}

{%- for thread in architecture.threads %}
K_THREAD_DEFINE(
    {{ thread.name }},
    {{ thread.stack_size or 1024 }},
    {{ thread.entry }},
    NULL, NULL, NULL,
    {{ thread.priority or 5 }},
    {{ thread.options or 0 }},
    {{ thread.delay or 0 }}
);
{%- endfor %}
""".strip()


def _render(template: str, architecture: Architecture) -> str:
    env = Environment(loader=BaseLoader())
    return env.from_string(template).render(architecture=architecture)


def generate_zbus_messages_h(architecture: Architecture) -> str:
    return _render(_ZBUS_MESSAGES_H_TEMPLATE, architecture)


def generate_zbus_channels_h(architecture: Architecture) -> str:
    return _render(_ZBUS_CHANNELS_H_TEMPLATE, architecture)


def generate_zbus_observers_c(architecture: Architecture) -> str:
    return _render(_ZBUS_OBSERVERS_C_TEMPLATE, architecture)
